// <auto-generated />
using System;
using CaseManagementApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseManagementApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250323232536_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseManagementApp.Models.Attorney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attorneys");
                });

            modelBuilder.Entity("CaseManagementApp.Models.BrownsteinCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttorneyId")
                        .HasColumnType("int");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseType")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttorneyId");

                    b.HasIndex("ClientId");

                    b.ToTable("BrownsteinCases");
                });

            modelBuilder.Entity("CaseManagementApp.Models.CaseNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttorneyId")
                        .HasColumnType("int");

                    b.Property<int?>("AttorneyId1")
                        .HasColumnType("int");

                    b.Property<int>("BrownsteinCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AttorneyId");

                    b.HasIndex("AttorneyId1");

                    b.HasIndex("BrownsteinCaseId");

                    b.ToTable("CaseNotes");
                });

            modelBuilder.Entity("CaseManagementApp.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CaseManagementApp.Models.BrownsteinCase", b =>
                {
                    b.HasOne("CaseManagementApp.Models.Attorney", "Attorney")
                        .WithMany()
                        .HasForeignKey("AttorneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagementApp.Models.Client", "Client")
                        .WithMany("BrownsteinCases")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attorney");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CaseManagementApp.Models.CaseNote", b =>
                {
                    b.HasOne("CaseManagementApp.Models.Attorney", "Attorney")
                        .WithMany()
                        .HasForeignKey("AttorneyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaseManagementApp.Models.Attorney", null)
                        .WithMany("CaseNotes")
                        .HasForeignKey("AttorneyId1");

                    b.HasOne("CaseManagementApp.Models.BrownsteinCase", "BrownsteinCase")
                        .WithMany("CaseNotes")
                        .HasForeignKey("BrownsteinCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attorney");

                    b.Navigation("BrownsteinCase");
                });

            modelBuilder.Entity("CaseManagementApp.Models.Attorney", b =>
                {
                    b.Navigation("CaseNotes");
                });

            modelBuilder.Entity("CaseManagementApp.Models.BrownsteinCase", b =>
                {
                    b.Navigation("CaseNotes");
                });

            modelBuilder.Entity("CaseManagementApp.Models.Client", b =>
                {
                    b.Navigation("BrownsteinCases");
                });
#pragma warning restore 612, 618
        }
    }
}
